image: java:8-jdk
stages:
 - test 
 - build
services:
 - 'mysql:5.5'
variables:
 MYSQL_DATABASE: newsdb
 MYSQL_CI_URL: jdbc:mysql://mysql/newsdb
 MYSQL_USER: app_root
 MYSQL_PASSWORD: root 
 MYSQL_ROOT_PASSWORD: root
cache:
 paths:
  - .m2/repository
  - target
maven-test:
 image: maven:3-jdk-8
 stage: test
 before_script: 
   - 'source ./beforeprojectServer.sh'
 script: 'mvn test -B'
 after_script: 
   - 'source ../afterprojectServer.sh'
maven-build:
 image: maven:3-jdk-8
 stage: build
 before_script: 
   - 'source ./beforeprojectServer.sh'
 script: 'mvn package -U'
 after_script: 
   - 'source ./afterprojectServer.sh'
 artifacts:
  paths: 
   - 'target/*.jar'
